server:
  port: 8081
spring:
  datasource:
    druid:
      name: init
      url: jdbc:postgresql://127.0.0.1:5432/test
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      filters: stat
      # 初始连接
      initialSize: 1
      # 最大连接数
      maxActive: 20
      # 获取的最长等待时
      maxWait: 60000
      # 最小空闲连接数
      minIdle: 1
      # 每一分钟执行空闲连接回收
      timeBetweenEvictionRunsMillis: 60000
      # 每十分钟回收空闲连接
      minEvictableIdleTimeMillis: 600000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
  servlet.multipart.max-file-size: 20MB
  servlet.multipart.max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    database: 6
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 20s
        min-idle: 5


mqtt:
  username: face
  password: face
  url: tcp://localhost:1883
  cleanSession: true
  connectionTimeout: 30
  keepAliveInterval: 60
  subscribe:
    clientId: finger-${random.uuid}
    topics: face/HSAC-RDFR3000-MC/+/rx
    qos: 0
    binary: true
    charset: UTF-8
  publish:
    clientId: finger-${random.uuid}
    topicPrefix:
    topic: face/HSAC-RDFR3000-MC/+/tx
    qos: 0
    retained: false
    charset: UTF-8
    async: false
    completionTimeout: 3000

logging.config:
        classpath: log4j2.properties

redis:
  key:
    defaultPrefix: init


